export default {
  MP_DATABASE:
    'Specify the local database filename to store persistent data. The default is a local temporary file which is auto-deleted when Mailpit exits. You can optionally use a remote rqlite database by specifying a “http address” (see docs).',
  MP_LABEL:
    'Set an optional label to identify this Mailpit instance. This adds the label to the web UI, SMTP and POP3 servers.',
  MP_TENANT_ID:
    'Set a tenant ID (table prefix). This is used to isolate the data from other Mailpit instances sharing the same data file (see docs).',
  MP_MAX_MESSAGES:
    'Maximum number of messages to store. Mailpit will periodically delete the oldest messages if greater than this. Set to 0 to disable auto-deletion (see docs).',
  MP_MAX_AGE:
    'Maximum age of messages to store in either (h)ours or (d)ays. Mailpit will periodically delete the oldest messages if greater than this. The value must be either in hours (eg: --max-age 36h) or days (eg: --max-age 14d) (see docs).',
  MP_USE_MESSAGE_DATES:
    'Use message header date as the Mailpit received date & time instead of the SMTP-received date & time.',
  MP_IGNORE_DUPLICATE_IDS: 'Ignore duplicate messages based on Message-Ids.',
  MP_LOG_FILE: 'Log Mailpit output to file instead of stdout. eg: --log-file /path/to/logfile.log',
  MP_QUIET: 'Quiet logging (errors only)',
  MP_VERBOSE: 'Verbose logging (debug)',
  MP_UI_BIND_ADDR: 'HTTP bind interface and port for UI.',
  MP_WEBROOT:
    'Set the webroot for web UI & API, for example mail would result in http://0.0.0.0:8025/mail/.',
  MP_UI_AUTH_FILE: 'Specify a password file for web UI & API basic authentication (see docs).',
  MP_UI_TLS_CERT:
    'TLS certificate for web UI & API (ie: HTTPS). This option requires the --ui-tls-key argument or MP_UI_TLS_KEY environment variable to be set.',
  MP_UI_TLS_KEY:
    'TLS key for web UI & API (ie: HTTPS). This option requires the --ui-tls-cert argument or MP_UI_TLS_CERT environment variable to be set.',
  MP_API_CORS:
    'Set API CORS Access-Control-Allow-Origin header if you require cross-domain browser requests.',
  MP_BLOCK_REMOTE_CSS_AND_FONTS:
    'Block all browser access to remote CSS and fonts imported via message stylesheets. Mailpit uses the HTTP Content Security Policy (CSP) method to block these. This does not block remote images or clicking on external link.',
  MP_ENABLE_SPAMASSASSIN:
    'Enable SpamAssassin integration for message spamminess score (see docs).',
  MP_ALLOW_UNTRUSTED_TLS:
    'Do not verify HTTPS certificates for either link checker & screenshot generation.',
  MP_SMTP_BIND_ADDR: 'SMTP bind interface and port.',
  MP_SMTP_AUTH_FILE: 'Specify a password file for SMTP authentication (see docs).',
  MP_SMTP_AUTH_ACCEPT_ANY:
    'Accept any SMTP username and password, including none. Use this to basically allow anything.',
  MP_SMTP_TLS_CERT:
    'TLS certificate for SMTP STARTTLS. This option requires the --smtp-tls-key argument or MP_SMTP_TLS_KEY environment variable to be set.',
  MP_SMTP_TLS_KEY:
    'TLS key for SMTP STARTTLS. This option requires the --smtp-tls-cert argument or MP_SMTP_TLS_CERT environment variable to be set.',
  MP_SMTP_REQUIRE_STARTTLS:
    'Require all SMTP clients to use STARTTLS encryption. If set to true, the only allowed commands are NOOP, EHLO, STARTTLS and QUIT (as specified in RFC 4954) until the connection is upgraded to STARTTLS.',
  MP_SMTP_REQUIRE_TLS:
    'Require all SMTP clients to use SSL/TLS encryption. If set to true, all connections to the SMTP server must be handled over TLS. This is different to STARTTLS which requires the initial connection to be unencrypted. Note that this option disables STARTTLS and may reduce client compatibility.',
  MP_SMTP_AUTH_ALLOW_INSECURE:
    'Typically either STARTTLS or TLS is enforced for all SMTP authentication. This option allows insecure PLAIN & LOGIN SMTP authentication when using STARTTLS.',
  MP_SMTP_STRICT_RFC_HEADERS:
    'Force Mailpit to return an SMTP error if message headers contain \\n instead to \\r\\n line breaks. By default Mailpit will silently fix incorrect line breaks generated by some broken sendmail clients (see related Github issue).',
  MP_SMTP_MAX_RECIPIENTS: 'Maximum number of SMTP recipients allowed per message.',
  MP_SMTP_ALLOWED_RECIPIENTS: `Only allow SMTP recipients matching a regular expression. Use this to restrict incoming mail to only those sent to a pre-defined list. An example would be --smtp-allowed-recipients '{'@'}example.com$' to only allow emails sent to recipients ending in {'@'}example.com.`,
  MP_SMTP_DISABLE_RDNS:
    'Disable SMTP reverse DNS lookups. SMTP will by default try resolve the hostname of the IP address of the connecting client, however in test networks this can sometimes be problematic causing delays for every message delivered.',
  MP_SMTP_RELAY_CONFIG:
    'SMTP configuration file to enable message relay/release (see docs). Alternatively the entire configuration can be passed via environment variables.',
  MP_SMTP_RELAY_ALL:
    'Automatically relay all incoming messages via external SMTP server (see docs). Use with extreme caution!',
  MP_SMTP_RELAY_MATCHING:
    'Automatically relay some incoming messages to matching recipients via external SMTP server (see docs).',
  MP_POP3_BIND_ADDR: 'POP3 server bind interface and port.',
  MP_POP3_AUTH_FILE: 'Specify a password file for POP3 authentication (see docs).',
  MP_POP3_TLS_CERT:
    'TLS certificate for POP3 SSL/TLS. This option requires the --pop3-tls-key argument or MP_POP3_TLS_KEY environment variable to be set.',
  MP_POP3_TLS_KEY:
    'TLS key for POP3 SSL/TLS. This option requires the --pop3-tls-cert argument or MP_POP3_TLS_CERT environment variable to be set.',
  MP_TAG: 'Auto-tag new messages matching filters (see docs).',
  MP_TAGS_CONFIG: 'Load tags filters from yaml configuration file (see docs).',
  MP_TAGS_TITLE_CASE: 'Enforces TitleCasing for all newly-created tags (see docs).',
  MP_TAGS_DISABLE:
    'Disable specific auto-tagging. This option takes a comma-separated list of options (see docs).',
  MP_WEBHOOK_URL:
    'Call a webhook when new messages are received (see docs), eg: --webhook-url https://example.com/webhook.php.',
  MP_WEBHOOK_LIMIT:
    'Rate limited webhook requests per second. To prevent potentially overloading the webhook server, this is rate limited by default to a maximum of 1 request per second (see docs).'
}
